### ISSUE TITLE
关于文章获取

### ISSUE THREAD

**Issue by jc-ryan** [cytan17726/KBQA_QueryGraphGeneration#3]
您好，恭喜获得CCKS2022最佳论文！
请问可以指引一下论文原文如何获取吗，一番检索下来没有发现如何获取到文章原文~
谢谢

**Comment by cytan17726** [comment]
您好，文章转投期刊中，待接收后我会在readme中更新最终稿的获取方式。
目前我可以给您提供会议提交版，您可以email我: cytan17726@stu.suda.edu.cn。
感谢您的issue！
